import ts from 'typescript';import fs from 'node:fs';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';
const compile=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
const url=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');const gameURL=url(compile(fs.readFileSync('lib/game.ts','utf8')));
const {validPlacement,placementLimit,wins,tick}=await import(gameURL);
assert.equal(placementLimit(1,[]),3);assert.equal(placementLimit(4,[]),3);assert.equal(placementLimit(4,[2]),5);
assert(!validPlacement(2,[0,1,2],[40,41,42,43,44],7));assert(validPlacement(2,[0,1,2],[2,3,4,5,6],7));assert(!validPlacement(2,[0],[0,0],7));assert(!validPlacement(4,[],[0,1,2,3],7));assert(!validPlacement(2,[0],[],7));
for(const cells of [[0,1,2,3,4],[0,7,14,21,28],[0,8,16,24,32],[4,10,16,22,28]])assert(wins(cells,7));assert(!wins([5,6,7,8,9],7));
const sql=new DatabaseSync(':memory:');sql.exec(fs.readFileSync('drizzle/0000_deep_karnak.sql','utf8'));
globalThis.testEnv={DB:{prepare(q){let v=[];return{bind(...values){v=values;return this},async first(){return sql.prepare(q).get(...v)},async run(){return{meta:{changes:sql.prepare(q).run(...v).changes}}}}}}};
const api=compile(fs.readFileSync('app/api/game/route.ts','utf8').replace("import { env } from 'cloudflare:workers';","const env=globalThis.testEnv;").replace("'@/lib/game'",JSON.stringify(gameURL)));
const {POST}=await import(url(api));const call=async(action,s={},extra={})=>{const res=await POST(new Request('https://test/api/game',{method:'POST',body:JSON.stringify({action,...s,...extra})}));return {status:res.status,...await res.json()}};
const a=await call('create',{}, {name:'A'}),A={code:a.room.code,token:a.token};const b=await call('join',{}, {code:A.code,name:'B'}),B={code:A.code,token:b.token};
await call('ready',A);await call('ready',B);await call('start',A);await call('draft',A,{round:1,cells:[0,1,2],submit:true});let r=await call('poll',B);assert(!('draft' in r.room.players.find(x=>x.id===a.room.me)));
await call('draft',B,{round:1,cells:[7,8,9],submit:true});let state=JSON.parse(sql.prepare('SELECT state FROM rooms WHERE code=?').get(A.code).state);state.bombRules=false;state.deadline=Date.now()-1;sql.prepare('UPDATE rooms SET state=? WHERE code=?').run(JSON.stringify(state),A.code);await call('poll',A);
r=await call('draft',A,{round:2,cells:[40,41,42,43,44],submit:true});assert.equal(r.status,400);
await call('draft',A,{round:2,cells:[0,1,2,3,4],submit:true});r=await call('draft',B,{round:2,cells:[7,8,9,10,11],submit:true});assert.equal(r.room.winners.length,2);
state=JSON.parse(sql.prepare('SELECT state FROM rooms WHERE code=?').get(A.code).state);state.phase='select';state.round=4;state.deadline=Date.now()+15000;state.players.forEach(p=>{p.positions=[];p.draft=[];p.submitted=false});sql.prepare('UPDATE rooms SET state=? WHERE code=?').run(JSON.stringify(state),A.code);
r=await call('draft',A,{round:4,cells:[0,1,2,3,4],submit:true});assert.equal(r.status,400);r=await call('draft',A,{round:4,cells:[0,1,2],submit:true});assert.equal(r.status,200);
console.log('PASS rules/API: anchor enforcement, reset to 3, privacy, directions, simultaneous winners');
