export type Player={id:string;token:string;name:string;seat:number;ready:boolean;submitted:boolean;positions:number[];draft:number[];seen:number;missed:number;active:boolean};
export type Room={code:string;host:string;phase:'lobby'|'select'|'reveal'|'finished';round:number;size:number;deadline:number;players:Player[];collisions:number[];winners:string[];reason?:string};
export function wins(cells:number[],size:number){const s=new Set(cells);for(const c of cells){const x=c%size,y=Math.floor(c/size);for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){if(Array.from({length:5},(_,i)=>[x+dx*i,y+dy*i]).every(([a,b])=>a>=0&&a<size&&b>=0&&b<size&&s.has(b*size+a)))return true;}}return false;}
export function startRound(r:Room,now:number){r.round++;r.phase='select';r.deadline=now+15000;r.collisions=[];for(const p of r.players){p.draft=[...p.positions];p.submitted=false;}}
export function tick(r:Room,now:number){if(r.phase==='select'&&(now>=r.deadline||r.players.filter(p=>p.active).every(p=>p.submitted))){let ps=r.players.filter(p=>p.active);for(const p of ps){p.missed=now-p.seen>12000?p.missed+1:0;if(p.missed>=2){p.active=false;p.positions=[];p.draft=[];}}ps=r.players.filter(p=>p.active);if(ps.length<2){r.phase='finished';r.winners=ps.map(p=>p.id);r.reason=ps.length?'다른 참가자가 퇴장하여 기권승':'참가자가 없어 종료되었습니다';return;}for(const p of ps){if(!validPlacement(r.round,p.positions,p.draft,r.size))p.draft=[...p.positions];}const count=new Map<number,number>();for(const p of ps)for(const c of p.draft)count.set(c,(count.get(c)||0)+1);r.collisions=[...count].filter(([,n])=>n>1).map(([c])=>c);for(const p of ps)p.positions=p.draft.filter(c=>count.get(c)===1);r.winners=ps.filter(p=>wins(p.positions,r.size)).map(p=>p.id);r.phase='reveal';r.deadline=now+2000;}else if(r.phase==='reveal'&&now>=r.deadline){if(r.winners.length)r.phase='finished';else startRound(r,now);}}
export function view(r:Room,token:string,now:number){const me=r.players.find(p=>p.token===token);return {...r,now,me:me?.id,players:r.players.map(({token,draft,...p})=>({...p,...(p.id===me?.id?{draft}: {})}))};}

export function placementLimit(round:number, positions:number[]){return round===1||positions.length===0?3:5;}
export function validPlacement(round:number,positions:number[],cells:number[],size:number){return cells.length<=placementLimit(round,positions)&&new Set(cells).size===cells.length&&cells.every(c=>Number.isInteger(c)&&c>=0&&c<size*size)&&(positions.length===0||cells.some(c=>positions.includes(c)));}
